openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

servers:
  - url: http://localhost:3000

paths:
  # Auth
  /api/auth/signup:
    $ref: './paths/auth.yaml#/signup'
  /api/auth/signin:
    $ref: './paths/auth.yaml#/signin'

  # User
  /api/users:
    $ref: './paths/user.yaml#/users'
  /api/users/{id}:
    $ref: './paths/user.yaml#/user'
  /api/users/me:
    $ref: './paths/user.yaml#/me'
