openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

servers:
  - url: http://localhost:3000

paths:
  # Auth
  /api/auth/signup:
    $ref: './paths/auth.yaml#/signup'
  /api/auth/signin:
    $ref: './paths/auth.yaml#/signin'

  # User
  /api/users:
    $ref: './paths/user.yaml#/users'
  /api/users/{id}:
    $ref: './paths/user.yaml#/user'
  /api/users/me:
    $ref: './paths/user.yaml#/me'

  # Category
  /api/categories:
    $ref: './paths/category.yaml#/categories'
  /api/categories/{id}:
    $ref: './paths/category.yaml#/category'

  # Product
  /api/products:
    $ref: './paths/product.yaml#/products'
  /api/products/{id}:
    $ref: './paths/product.yaml#/product'
  /api/products/{id}/thumbnail:
    $ref: './paths/product.yaml#/thumbnail'
  /api/products/{id}/images:
    $ref: './paths/product.yaml#/images'

  # Order
  /api/orders:
    $ref: './paths/order.yaml#/orders'
  /api/orders/{id}:
    $ref: './paths/order.yaml#/order'
