# create:
#   type: object
#   properties:
#     title:
#       type: string
#       example: 'Wireless Mouse'
#     description:
#       type: string
#       example: 'High-quality wireless mouse with ergonomic design'
#     category_id:
#       type: string
#       example: '1234567890'
#     price:
#       type: number
#       example: 50
#     stock:
#       type: number
#       example: 100
#     thumbnail:
#       type: string
#       format: binary
#       description: 'Product thumbnail image (single file)'
#     product_feature_images:
#       type: array
#       items:
#         type: string
#         format: binary
#       description: 'Multiple feature images (max 5 files)'
#   required:
#     - title
#     - description
#     - category_id
#     - price
#     - stock

pp:
  type: object
  properties:
    title:
      type: string
      example: 'Wireless Mouse'
    description:
      type: string
      example: 'High-quality wireless mouse with ergonomic design'
    category_id:
      type: string
      example: '1234567890'
    price:
      type: number
      example: 50
    stock:
      type: number
      example: 100
    thumbnail:
      type: string
      format: binary
      description: 'Product thumbnail image (single file)'
    product_feature_images:
      type: array
      items:
        type: string
        format: binary
      description: 'Multiple feature images (max 5 files)'
  required:
    - title
    - description
    - category_id
    - price
    - stock

create:
  type: object

# update:
#   type: object
#   properties:
#     title:
#       type: string
#       example: 'Wireless Mouse'
# description:
#   type: string
#   example: 'High-quality wireless mouse with ergonomic design'
# category_id:
#   type: string
#   example: '1234567890'
# price:
#   type: number
#   example: 50
# stock:
#   type: number
#   example: 100

# Change the thumbnail image of a product
changeThumbnail:
  type: object
  properties:
    thumbnail:
      type: string
      format: binary
      description: 'Product thumbnail image (single file)'
  required:
    - thumbnail

# Add feature images to a product
images:
  type: object
  properties:
    product_feature_images:
      type: array
      items:
        type: string
        format: binary
      description: 'Multiple feature images (max 5 files)'
  required:
    - product_feature_images
